### ISSUE TITLE
Confused by the glib_wrapper macro

### ISSUE THREAD

**Issue by gkoz** [GuillaumeGomez/rustdoc-stripper#10]
Apparently the parser doesn't handle the `glib_wrapper!` macro.
https://github.com/gtk-rs/gtk/blob/master/src/auto/tree_iter.rs#L7-L8
https://github.com/gtk-rs/rustdoc-comments/blob/master/gtk/comments.cmts#L172-L173

**Comment by GuillaumeGomez** [comment]
I can confirm easily that it doesn't. It just handles macro declaration, not usage. It might need an update to fix this.

**Comment by GuillaumeGomez** [comment]
I confirm, when a macro is "the parent", then it should be ignored and the macro's parent should be directly used.

**Comment by GuillaumeGomez** [comment]
It has been fixed by #13.
