### ISSUE TITLE
Macro issue

### ISSUE THREAD

**Issue by GuillaumeGomez** [GuillaumeGomez/rustdoc-stripper#14]
Another issue linked to macros. Actually, if you have doc comments on objects inside macros, it won't be generated back because of #13.

cc @gkoz

**Comment by gkoz** [comment]
Yeah, we need both stripper and regenerator to handle them.

**Comment by GuillaumeGomez** [comment]
Can you provide an example that please? I think I misunderstood what you wanted.

**Comment by gkoz** [comment]
```
glib_wrapper! {
    /// This struct's documentation should be slurped buy the stripper
    /// and restored by the regenerator same as any other struct.
    pub struct TreeIter(Boxed<ffi::GtkTreeIter>);
```

**Comment by gkoz** [comment]
To be precise, the fact that it's inside the macro invocation should not be reflected in the cmts file because that would be distracting and unhelpful.

**Comment by GuillaumeGomez** [comment]
Yes, and it's what's happening with the current version. However, it is problematic if we want it to keep the full hierarchy. What about adding an option to make the difference between the two modes? Adding `--ignore-macros` seems to be a nice idea.

**Comment by gkoz** [comment]
Technically the stripper ignores macros already but produces garbage (has the issue been closed too early?):
```
=! src/auto/tree_iter.rs
=| use glib::translate::*;struct TreeIter
    /// ABCDE
```
I just want the `=|` line to be correct.

**Comment by GuillaumeGomez** [comment]
Hum, strange indeed.
