### ISSUE TITLE
Regenerator tries to document commented out functions

### ISSUE THREAD

**Issue by gkoz** [GuillaumeGomez/rustdoc-stripper#21]
```rust
impl Impl {
    //pub fn func() { }
}
```
```
=! file.rs
=| impl Impl§fn func
    /// This is func
```

**Comment by GuillaumeGomez** [comment]
Oh interesting, I didn't think of removing commented code!

**Comment by gkoz** [comment]
It doesn't need to be removed but not documented either.

**Comment by GuillaumeGomez** [comment]
No I mean in the parsing part, before it I'll remove comments from code, it'll be easier to process on it therefore.
