### ISSUE TITLE
Generic fns parsing

### ISSUE THREAD

**Issue by gkoz** [GuillaumeGomez/rustdoc-stripper#22]
```rust
impl Struct {
    /// This is func
    pub fn func<T: Foo>() { }
}
```
Expected output:
```
=! file.rs
=| impl Struct§fn func
    /// This is func
```
Actual:
```
=! file.rs
=| impl Struct§fn func<T
    /// This is func
```
Affects regenerator too.

**Comment by GuillaumeGomez** [comment]
No, it's almost the expected output. I handle type parameters (incorrectly as it seems) as a precision on the object.

**Comment by gkoz** [comment]
There is no function overloading.

**Comment by GuillaumeGomez** [comment]
No, the point here was to differentiate a function if the type parameter changed between the strip and the regeneration. Cerainly useless now that I think about it...
