### ISSUE TITLE
Is there reason for `crate-type`?

### ISSUE THREAD

**Issue by ignatenkobrain** [GuillaumeGomez/rustdoc-stripper#48]
```
crate-type = ["dylib", "rlib"]
```

This is in Cargo.toml and I'm working on generator for RPM packages for crates. At this point, we don't allow dynamic / static libraries to be packaged because rust doesn't have stable ABI. My question is why do we need to have this types even specified in toml? Is there some reason behind?

Thanks a lot for understanding!

**Comment by GuillaumeGomez** [comment]
It's been done quite a long time ago. At the time, you were required to specify which kind of built object you wanted (and you required both for windows if I recall correctly for some forgotten reasons...). I suspect this line being completely useless now.

**Comment by ignatenkobrain** [comment]
@GuillaumeGomez thanks for explanation, proposed #49 to remove it.
