### ISSUE TITLE
Docs not embedded for traits anymore

### ISSUE THREAD

**Issue by EPashkin** [GuillaumeGomez/rustdoc-stripper#53]
Ex. for gio `cargo build --features "embed-lgpl-docs"` in file auto/settings_backend.rs functions in `pub trait SettingsBackendExt: 'static` not updated despite docs present.

```
<!-- trait SettingsBackendExt::fn path_writable_changed -->
Signals that the writability of all keys below a given path may have
changed.
```

**Comment by GuillaumeGomez** [comment]
Arf, not good...

**Comment by EPashkin** [comment]
Current version https://gtk-rs.org/docs/gio/trait.SocketListenerExt.html also don't contains docs, so problem was at minimum on previous release

**Comment by EPashkin** [comment]
For gtk comments not generated for these traits PadControllerExtManual, TreeSortableExtManual, EditableSignals etc., config in https://github.com/gtk-rs/gtk/pull/832
