### ISSUE TITLE
Path comparison of ignored files should be improved

### ISSUE THREAD

**Issue by GuillaumeGomez** [GuillaumeGomez/rustdoc-stripper#7]
The comparison is [here](https://github.com/GuillaumeGomez/rustdoc-stripper/blob/master/src/utils.rs#L50) and should use the [canonicalize](http://static.rust-lang.org/doc/master/std/path/struct.Path.html#method.canonicalize) method to fully work.

Also, the canonicalize method needs to be used when file to ignore is added as well.

**Comment by gkoz** [comment]
Fixed in #17
