### ISSUE TITLE
Use doc aliases for finding where to inject documentation

### ISSUE THREAD

**Issue by sdroege** [GuillaumeGomez/rustdoc-stripper#74]

**Comment by sdroege** [comment]
Also if there are multiple aliases on the same item it should only consider the first one, I guess.

**Comment by GuillaumeGomez** [comment]
I'm still a bit lost of why you want to use doc aliases to find out where to inject doc.

**Comment by sdroege** [comment]
Because that makes it unecessary to add complicated `manual = true` and `rename = "..."` things in the `Gir.toml`. `manual` and `ignore` could be exactly the same again.

**Comment by sdroege** [comment]
As discussed this doesn't make any sense because of how rustdoc-stripper works. @GuillaumeGomez can add some more details if needed.
