### ISSUE TITLE
Allow disregarding file names for non-module comments in regenerator

### ISSUE THREAD

**Issue by gkoz** [GuillaumeGomez/rustdoc-stripper#9]
Say I have some documentation.
```
=| struct Foo
/// foo
=| impl Foo§fn bar
    /// bar
```
I don't really care which file this is going to end up at. I just want these struct and function to get their comments. A struct or a function could move between `auto` and `src` directories for various reasons. Functions for a particular struct can be present in more than one file. The generator doesn't have perfect knowledge of target file names.

Either add it as an option or change the current algo.

**Comment by gkoz** [comment]
Or perhaps treat `=! ?` as a catch-all file and look for documentation for `foo.rs` in both `foo.rs` and `?`.

**Comment by GuillaumeGomez** [comment]
The algo can't make a difference if the path to the object we're adding back comments on is the same. We could do it, but then it'll surely create issues.

**Comment by gkoz** [comment]
Done in #11
